### PR TITLE
Setup sbt-typelevel

### PR DESCRIPTION
**Pull request by armanbilge**
This is a pretty alien build to me so no idea what I'm doing 😆

### CODE REVIEW

**Comment by armanbilge** [comment]
Hmm, have actions been enabled on this repo?

**Comment by DavidGregory084** [comment]
Hmm that's weird, is it possible that Actions needs to be set up on main before it will run for a PR? 

On a completely different note, is this possibly one of those dependency cycle risks @armanbilge if we make sbt-typelevel depend on typelevel-scalafix at some later date?

**Comment by armanbilge** [comment]
> Hmm that's weird, is it possible that Actions needs to be set up on main before it will run for a PR?

No, I don't think so. I think actions is literally not enabled, e.g. look at https://github.com/typelevel/typelevel-scalafix/actions

> is this possibly one of those dependency cycle risks @armanbilge if we make sbt-typelevel depend on typelevel-scalafix at some later date?

I don't think so. Or at least it's a weaker cycle than the sbt-tpolecat situation. For example, when sbt 2.0 arrives sbt-typelevel should be able to upgrade without typelevel-scalafix changing anything.

**Comment by armanbilge** [comment]
Yeah, maybe you're right. But I'm baffled, I didn't think it used to be like that. Could be wrong.

**Comment by DavidGregory084** [comment]
OK that silly trick seems to have worked 🤯

**Comment by DavidGregory084** [comment]
One thing I am not sure about here - the Scalafix rule template uses [sbt-projectmatrix](https://github.com/sbt/sbt-projectmatrix), which works in a completely different way to sbt's built-in crossbuilding. I wonder if we might need to rip that out for it to work nicely with sbt-typelevel. I guess we will find out!

**Comment by armanbilge** [comment]
> I wonder if we might need to rip that out for it to work nicely with sbt-typelevel. I guess we will find out!

It works okay-ish, I've set up a couple projects using projectmatrix. The part that breaks is splitting CI on scala version (e.g. the job above says it's running for 2.12.15 but it's actually running all the projects for whatever scala version they are set to).

**Comment by DavidGregory084** [comment]
Looks great, let's go! 🚀

**Pull request merged**
