### PR TITLE
UnusedShowInterpolator rule that detects use of the show interpolator without any interpolated variables

### LINKED ISSUE #17: Idea: show interpolation without variables
A simple rule that looks at `show"foobar"` strings and warns if there is no variable inside the interpolation.

```scala
val foo = "foo"
val a = show"$foo" // Should pass
val b = show"foo" // Should fail
val c = show"${foo}" // Should pass
```

### PR DESCRIPTION
**Pull request by DavidGregory084**
Fixes #17

### CODE REVIEW

**Comment by DavidGregory084** [comment]
Hmm have you seen this one before @armanbilge?
```
[error] java.lang.RuntimeException: not a directory or jar file: /home/runner/work/typelevel-scalafix/typelevel-scalafix/target/rules-aggregate/target/scala-2.13/classes
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at com.typesafe.tools.mima.lib.MiMaLib.$anonfun$createPackage$1(MiMaLib.scala:13)
[error] 	at scala.Option.getOrElse(Option.scala:189)
[error] 	at com.typesafe.tools.mima.lib.MiMaLib.createPackage(MiMaLib.scala:13)
```
when trying to run `typelevel-scalafix-rules / mimaReportBinaryIssues`, so it's specifically the binary compatibility check for the aggregate module.
It seems to be complaining that the class files are missing, but this is an aggregate module so I don't think there will ever be any.

**Comment by armanbilge** [comment]
Ooh, ouch. I wonder if it's technically a MiMa bug (i.e. it should handle this situation more gracefully). I guess we can set `mimaPreviousArtifacts := Set.empty` for that aggregate module. I generally try to avoid this (esp. for temporary fixes) but seems appropriate in this situation.

**Review by armanbilge — COMMENTED** [review]
Looks good! Question: can we implement this rule as a rewrite? Apologies if that's what you've done here 😅 in which case, doesn't it need an `output/` test?

**Comment by DavidGregory084** [comment]
> Looks good! Question: can we implement this rule as a rewrite? Apologies if that's what you've done here 😅 in which case, doesn't it need an `output/` test?

Hmm I feel a bit weird about implementing this as a rewrite - if the user didn't mean to add an interpolation then a rewrite works well, but if they did, it silently changes their code in a way that removes the warning that could have alerted them that they've forgotten something. What do you think, is that a bit too hypothetical of a concern?

**Comment by armanbilge** [comment]
Ahh, absolutely. Been there done that :) 👍

**Review by armanbilge — APPROVED** [review]

**Pull request merged**
